prepbufr_mnemonics_dict = {
'PW2Q': '0.9 TO 0.7 SIGMA LAYER PRECIP. WATER (QUALITY) MARKER',\
'PW2P': '0.9 TO 0.7 SIGMA LAYER PRECIP. WATER EVENT PROGRAM CODE',\
'T__EVENT': 'TEMPERATURE EVENT SEQUENCE',\
'PW2R': '0.9 TO 0.7 SIGMA LAYER PRECIP. WATER EVENT REASON CODE',\
'T__POSTP': 'TEMPERATURE POSTPROCESSING SEQUENCE',\
'PW2A': 'ANALYZED 0.9 TO 0.7 SIGMA LAYER PRECIP. WATER VALUE',\
'WFC__MSQ': 'MODEL WIND FORECAST SEQUENCE',\
'TP24': 'TOTAL PRECIPITATION PAST 24 HOURS',\
'YCOR': 'INDICATOR WHETHER LAT IN "YOB" WAS CORRECTED FRM "YORG"',\
'PW2E': '0.9 TO 0.7 SIGMA LAYER PRECIP. WATER OBSERVATION ERROR',\
'PREWXSEQ': 'PRESENT WEATHER SEQUENCE',\
'XCOR': 'INDICATOR WHETHER LON IN "XOB" WAS CORRECTED FRM "XORG"',\
'PW2O': '0.9 TO 0.7 SIGMA LAYER PRECIPITABLE WATER OBSERVATION',\
'PW3EVENT': '0.7 TO 0.3 PRECIPITABLE WATER EVENT SEQUENCE',\
'UAN': 'ANALYZED U-COMPONENT WIND VALUE',\
'TAN': 'ANALYZED TEMPERATURE VALUE',\
'MSST': 'METHOD OF SEA SURFACE TEMPERATURE MEASUREMENT',\
'VAN': 'ANALYZED V-COMPONENT WIND VALUE',\
'WRC': 'U-, V-COMPONENT WIND (UOB/VOB) EVENT REASON CODE',\
'SFCSHP': 'SURFACE MARINE (SHIP, BUOY, C-MAN PLATFORM) REPORTS',\
'ADPUPA': 'UPPER-AIR (RAOB, PIBAL, RECCO, DROPS) REPORTS',\
'DF_EVENT': 'WIND (DIRECTION/SPEED) EVENT SEQUENCE',\
'TURB3SEQ': 'TURBULENCE SEQUENCE # 3',\
'QQM': 'SPECIFIC HUMIDITY (QUALITY) MARKER',\
'E1': 'ERS ERROR ESTIMATE NUMBER 1',\
'SPSSMI': 'SSM/I RETRIEVAL PRODUCTS (REPROCESSED WIND SPEED, TPW)',\
'PQM': 'PRESSURE (QUALITY) MARKER',\
'CLOUDSEQ': 'OBSERVED CLOUD SEQUENCE # 1',\
'SNOW_SEQ': 'SNOW DEPTH SEQUENCE',\
'ZQM': 'HEIGHT (QUALITY) MARKER',\
'CTCN': 'CROSS TRACK CELL NUMBER (QUIKSCAT & ASCAT REPORTS ONLY)',\
'ACID_SEQ': 'AIRCRAFT FLIGHT NUMBER SEQUENCE',\
'TFC__MSQ': 'MODEL TEMPERATURE FORECAST SEQUENCE',\
'QFC__MSQ': 'MODEL SPECIFIC HUMIDITY FORECAST SEQUENCE',\
'PCS': 'STANDARD DEVIATION OF CLIMATOLOGICAL PRESSURE VALUE',\
'SID': 'STATION IDENTIFICATION',\
'TSB': 'REPORT SUBTYPE (HAS VARIOUS MEANINGS DEPENDING ON TYPE)',\
'UOB': 'U-COMPONENT WIND OBSERVATION (M/S)',\
'PCL': 'CLIMATOLOGICAL PRESSURE VALUE',\
'VADWND': 'VAD (NEXRAD) WIND REPORTS',\
'TOPC': 'TOTAL PRECIPITATION/TOTAL WATER EQUIVALENT',\
'SST_INFO': 'SEA TEMPERATURE INFORMATION',\
'PREVENT': 'PRE-EVENTS BACKGROUND/OBSERVATION ERROR PROCESSING STEP',\
'GUST1SEQ': 'MAXIMUM WIND GUST SEQUENCE # 1',\
'RF10M': '10 METER WIND REDUCTION FACTOR',\
'PAN': 'ANALYZED PRESSURE VALUE',\
'ELEV': 'SATELLITE ELEVATION (ZENITH ANGLE)',\
'TMXMNSEQ': 'MAXIMUM/MINIMUM TEMPERATURE SEQUENCE',\
'CTPQM': 'CLOUD TOP PRESSURE (QUALITY) MARKER',\
'MSTQ': 'MOISTURE QUALITY',\
'PCLIMATO': 'PRESSURE CLIMATOLOGY SEQUENCE',\
'SAID': 'SATELLITE IDENTIFIER (SATELLITE REPORTS ONLY)',\
'MWD10': 'MODEL WIND DIRECTION AT 10 M',\
'CQCVAD': 'VAD WIND QUALITY CONTROL STEP',\
'PW1F_MSQ': 'MODEL 1.0 TO 0.9 SIGMA LAYER PRECIP WATER FORECAST SEQ.',\
'SOEL': 'SOLAR ELEVATION (ZENITH ANGLE)',\
'ALTIMSEQ': 'ALTIMETER SETTING SEQUENCE',\
'SSTRC': 'SEA TEMPERATURE EVENT REASON CODE',\
'S3': 'ERS BACKSCATTER NUMBER 3',\
'S2': 'ERS BACKSCATTER NUMBER 2',\
'S1': 'ERS BACKSCATTER NUMBER 1',\
'IALR': 'INSTANTANEOUS ALTITUDE RATE',\
'RADCOR': 'RAWINSONDE HEIGHT/TEMP INTERSONDE(RADIATION) CORR. STEP',\
'ACID': 'AIRCRAFT FLIGHT NUMBER',\
'RRTBACKG': 'RAIN RATE BACKGROUND SEQUENCE',\
'ERS1DA': 'ERS SCATTEROMETER DATA (REPROCESSED WIND SPEED)',\
'CLAM': 'CLOUD AMOUNT',\
'POWV': 'PERIOD OF WAVES',\
'POWW': 'PERIOD OF WIND WAVES',\
'RCT': 'RECEIPT TIME',\
'BTMPINFO': 'TOVS OR GOES BRIGHTNESS TEMPERATURE INFORMATION',\
'DFQ': 'WIND DIRECTION/SPEED (DDO/FFO) (QUALITY) MARKER',\
'DFP': 'WIND DIRECTION/SPEED (DDO/FFO) EVENT PROGRAM CODE',\
'DFR': 'WIND DIRECTION/SPEED (DDO/FFO) EVENT REASON CODE',\
'HOSW': 'HEIGHT OF SWELL WAVES',\
'SYNDAT': 'SYNTHETIC TROPICAL CYCLONE BOGUS REPORTS',\
'PW4FMOD': 'MODEL .3-0. SIG. LYR PWATER FCST(GLOBAL MODEL SEE PW4F)',\
'DGOT': 'DEGREE OF TURBULENCE',\
'PW1FMOD': 'MODEL 1.-.9 SIG. LYR PWATER FCST(GLOBAL MODEL SEE PW1F)',\
'UFCMOD': 'MODEL U-COMPONENT FORECAST VALUE (GLOBAL MODEL SEE UFC)',\
'MRWVC': 'MWR WATER VAPOR CONTENT (TOTAL WATER VAPOR)',\
'TRBX32': 'TURBULENCE INDEX FOR PERIOD (TOB-3 MIN) -> (TOB-2 MIN)',\
'WQM': 'U-, V-COMPONENT WIND (UOB/VOB) (QUALITY) MARKER',\
'PW4F_MSQ': 'MODEL 0.3 TO 0.0 SIGMA LAYER PRECIP WATER FORECAST SEQ.',\
'PW2F': 'FCST(BACKGRND) 0.9 TO 0.7 SIGMA LYR PRECIP. WATER VALUE',\
'GPSIPW': 'GLOBAL POSITIONING SATELLITE-INTEGRATED PRECIP. WATER',\
'QOETU': 'ANALYSIS-TUNED RELATIVE HUMIDITY OBSERVATION ERROR',\
'CAT': 'PREPBUFR DATA LEVEL CATEGORY',\
'MITM': 'MINIMUM TEMPERATURE',\
'ACARSQC': 'MDCRS ACARS AIRCRAFT QUALITY CONTROL STEP',\
'TOB': 'TEMPERATURE OBSERVATION (DEGREES C)',\
'TOE': 'TEMPERATURE OBSERVATION ERROR (DEGREES C)',\
'RRTPC': 'RAINFALL (AVERAGE RATE) EVENT PROGRAM CODE',\
'BSCD': 'BACKSCATTER DISTANCE (ASCAT REPORTS ONLY)',\
'PW1O': '1.0 TO 0.9 SIGMA LAYER PRECIPITABLE WATER OBSERVATION',\
'PW1A': 'ANALYZED 1.0 TO 0.9 SIGMA LAYER PRECIP. WATER VALUE',\
'PFCMOD': 'MODEL PRESSURE FORECAST VALUE (GLOBAL MODEL SEE PFC)',\
'PW1F': 'FCST(BACKGRND) 1.0 TO 0.9 SIGMA LYR PRECIP. WATER VALUE',\
'HOCT_SEQ': 'HEIGHT OF TOP OF CLOUD SEQUENCE',\
'SOB': 'WIND SPEED OBSERVATION',\
'XOB': 'LONGITUDE (DEG E)',\
'PW1P': '1.0 TO 0.9 SIGMA LAYER PRECIP. WATER EVENT PROGRAM CODE',\
'PW1Q': '1.0 TO 0.9 SIGMA LAYER PRECIP. WATER (QUALITY) MARKER',\
'PW1R': '1.0 TO 0.9 SIGMA LAYER PRECIP. WATER EVENT REASON CODE',\
'PWETU': 'ANALYSIS-TUNED TOTAL PRECIPITABLE WATER OBS ERROR',\
'TP12_SEQ': 'TOTAL PRECIPITATION PAST 12 HOURS SEQUENCE',\
'PKWDDR': 'PEAK WIND DIRECTION',\
'CHPT': 'CHARACTERISTIC OF PRESSURE TENDENCY',\
'TFC': 'FORECAST (BACKGROUND) TEMPERATURE VALUE',\
'TURB1SEQ': 'TURBULENCE SEQUENCE # 1',\
'PW2_INFO': '0.9 TO 0.7 SIGMA LAYER PRECIPITABLE WATER INFORMATION',\
'EXPRSRD': 'EXPIRATION OF RESTRICTIONS ON REDISTRIBUTION',\
'VFC': 'FORECAST (BACKGROUND) V-COMPONENT WIND VALUE',\
'CTPOE': 'CLOUD TOP PRESSURE OBSERVATION ERROR',\
'PW1POSTP': '1.0 TO 0.9 SIGMA LAYER PRECIP WATER POSTPROCESSING SEQ.',\
'WOETU': 'ANALYSIS-TUNED WIND OBSERVATION ERROR',\
'PRC': 'PRESSURE EVENT REASON CODE',\
'QPC': 'SPECIFIC HUMIDITY EVENT PROGRAM CODE',\
'P__POSTP': 'PRESSURE POSTPROCESSING SEQUENCE',\
'ADPSFC': 'SURFACE LAND (SYNOPTIC, METAR) REPORTS',\
'ZFC__MSQ': 'MODEL HEIGHT FORECAST SEQUENCE',\
'CTPFC': 'FORECAST (BACKGROUND) CLOUD TOP PRESSURE VALUE',\
'TPC': 'TEMPERATURE EVENT PROGRAM CODE',\
'RFFL': 'PERCENT CONFIDENCE BASED ON NESDIS RECURSIVE FILTER FCN',\
'PSW2': 'PAST WEATHER (2)',\
'PSW1': 'PAST WEATHER (1)',\
'NRLACQC': 'NRL AIRCRAFT QUALITY CONTROL STEP',\
'CTPEVENT': 'CLOUD TOP PRESSURE EVENT SEQUENCE',\
'PW2POSTP': '0.9 TO 0.7 SIGMA LAYER PRECIP WATER POSTPROCESSING SEQ.',\
'PW1EVENT': '1.0 TO 0.9 PRECIPITABLE WATER EVENT SEQUENCE',\
'VISB2SEQ': 'VISIBILITY SEQUENCE # 2',\
'HOVI': 'HORIZONTAL VISIBILITY (M)',\
'POAF': 'PHASE OF AIRCRAFT FLIGHT',\
'GUST2SEQ': 'MAXIMUM WIND GUST SEQUENCE # 2',\
'TYP': 'PREPBUFR REPORT TYPE',\
'PW4F': 'FCST(BACKGRND) 0.3 TO 0.0 SIGMA LYR PRECIP. WATER VALUE',\
'PW4E': '0.3 TO 0.0 SIGMA LAYER PRECIP. WATER OBSERVATION ERROR',\
'HEADR': 'REPORT HEADER SEQUENCE',\
'PW4A': 'ANALYZED 0.3 TO 0.0 SIGMA LAYER PRECIP. WATER VALUE',\
'PW4O': '0.3 TO 0.0 SIGMA LAYER PRECIPITABLE WATER OBSERVATION',\
'CTPPC': 'CLOUD TOP PRESSURE EVENT PROGRAM CODE',\
'PW4R': '0.3 TO 0.0 SIGMA LAYER PRECIP. WATER EVENT REASON CODE',\
'PW4Q': '0.3 TO 0.0 SIGMA LAYER PRECIP. WATER (QUALITY) MARKER',\
'PW4P': '0.3 TO 0.0 SIGMA LAYER PRECIP. WATER EVENT PROGRAM CODE',\
'FFO': 'WIND SPEED OBSERVATION (NOT ASSIMILATED)',\
'ASMP': 'AVG SPD OF SHIP DURING PAST 3 HOURS',\
'CHSQ': 'CHI-SQUARED (OF THE WIND VECTOR RETRIEVAL)',\
'QOE': 'RELATIVE HUMIDITY OBSERVATION ERROR (PERCENT DIVIDED BY 10)',\
'SFCBOG': 'MEAN SEA-LEVEL PRESSURE BOGUS REPORTS',\
'QOB': 'SPECIFIC HUMIDITY OBSERVATION (MG/KG)',\
'PW3POSTP': '0.7 TO 0.3 SIGMA LAYER PRECIP WATER POSTPROCESSING SEQ.',\
'E3': 'ERS ERROR ESTIMATE NUMBER 3',\
'E2': 'ERS ERROR ESTIMATE NUMBER 2',\
'PKWDSP': 'PEAK WIND SPEED',\
'ESBAK': 'FORECAST(BACKGROUND) SATURATION SPECIFIC HUMIDITY VALUE',\
'SATWND': 'SATELLITE-DERIVED WIND REPORTS',\
'PW1E': '1.0 TO 0.9 SIGMA LAYER PRECIP. WATER OBSERVATION ERROR',\
'TOETU': 'ANALYSIS-TUNED TEMPERATURE OBSERVATION ERROR',\
'PHER': 'EST. ERROR COVARIANCE FOR WIND DIRECTION RETRIEVAL',\
'WCLIMATO': 'WIND CLIMATOLOGY SEQUENCE',\
'WOE': 'WIND OBSERVATION ERROR (M/S)',\
'POSW': 'PERIOD OF SWELL WAVES',\
'SCATINFO': 'SCATTEROMETER DATA INFORMATION',\
'CLDE': 'EST. ERROR COVARIANCE FOR TOTAL CLD LIQUID WATER RETR.',\
'RRTPOSTP': 'RAIN RATE POSTPROCESSING SEQUENCE',\
'SSI': 'SSI GLOBAL ANALYSIS STEP',\
'ZRC': 'HEIGHT EVENT REASON CODE',\
'PW2FMOD': 'MODEL .9-.7 SIG. LYR PWATER FCST(GLOBAL MODEL SEE PW2F)',\
'Z___INFO': 'HEIGHT INFORMATION',\
'RASSDA': 'RADIO ACOUSTIC SOUNDING SYSTEM (RASS) TEMP PROFILE RPTS',\
'PTE24SEQ': '24 HOUR PRESSURE TENDENCY SEQUENCE',\
'RRTFC': 'FORECAST (BACKGROUND) RAINFALL (AVERAGE RATE) VALUE',\
'HRDR': 'PROFILE LVL TIME-CYCLE (FOR RAOB/PIBAL, BASED ON B DFT, HOURS)',\
'ACFT_SEQ': 'AIRCRAFT SUPPLEMENTARY DATA SEQUENCE',\
'POETU': 'ANALYSIS-TUNED PRESSURE OBSERVATION ERROR',\
'P__BACKG': 'PRESSURE BACKGROUND SEQUENCE',\
'NUL': 'NULL (IGNORE)',\
'RRTOE': 'RAINFALL (AVERAGE RATE) OBSERVATION ERROR',\
'TDMP': 'TRUE DIRECTION OF SHIP DURING PAST 3 HOURS',\
'WPC': 'U-, V-COMPONENT WIND (UOB/VOB) EVENT PROGRAM CODE',\
'TOSS': 'TOTAL SUNSHINE',\
'CDTP': 'CLOUD TOP PRESSURE OBSERVATION',\
'W__EVENT': 'WIND EVENT SEQUENCE',\
'CLIMO': 'CLIMOTOLOGICAL PROCESSING STEP',\
'XS20': '20 METER EXTRAPOLATED WIND SPEED',\
'TOSD': 'TOTAL SNOW DEPTH',\
'QFC': 'FORECAST (BACKGROUND) SPECIFIC HUMIDITY VALUE',\
'PREPRO': 'INITIAL PREPBUFR PROCESSING STEP',\
'SYNDATA': 'SYNTHETIC TROPICAL CYCLONE BOGUS PROCESSING STEP',\
'PKWNDSEQ': 'PEAK WIND SEQUENCE',\
'ITP': 'INSTRUMENT TYPE',\
'Q__POSTP': 'SPECIFIC HUMIDITY POSTPROCESSING SEQUENCE',\
'PWTVWTA': 'ANAL VARIAT. QC WGHT ON TOT PREC. WTR OBS BASED ON ANAL',\
'TCLIMATO': 'TEMPERATURE CLIMATOLOGY SEQUENCE',\
'PWTVWTG': 'ANAL VARIAT. QC WGHT ON TOT PREC. WTR OBS BASED ON GESS',\
'RPT': 'REPORTED OBSERVATION TIME',\
'TP01': 'TOTAL PRECIPITATION PAST 1 HOUR',\
'TP03': 'TOTAL PRECIPITATION PAST 3 HOURS',\
'VTVI_SEQ': 'VERTICAL VISIBILITY SEQUENCE',\
'TP06': 'TOTAL PRECIPITATION PAST 6 HOURS',\
'POE': 'PRESSURE OBSERVATION ERROR (MB)',\
'POB': 'PRESSURE OBSERVATION (MB)',\
'PW2BACKG': '0.9 TO 0.7 SIGMA LAYER PRECIP WATER BACKGROUND SEQUENCE',\
'TURB2SEQ': 'TURBULENCE SEQUENCE # 2',\
'PW__INFO': 'PRECIPITABLE WATER INFORMATION',\
'PWA': 'ANALYZED TOTAL PRECIPITABLE WATER VALUE',\
'VCL': 'CLIMATOLOGICAL V-COMPONENT WIND VALUE',\
'VCS': 'STANDARD DEVIATION OF CLIMATOLOGICAL V-COMP WIND VALUE',\
'SSTQM': 'SEA TEMPERATURE (QUALITY) MARKER',\
'DHR': 'OBSERVATION TIME MINUS CYCLE TIME (HOURS)',\
'VIRTMP': 'VIRTUAL TEMPERATURE/SPECIFIC HUMIDITY PROCESSING STEP',\
'24PC': '24 HOUR PRESSURE CHANGE',\
'PVWTG': 'ANAL VARIATIONAL QC WEIGHT ON PRESS. OBS BASED ON GUESS',\
'PVWTA': 'ANAL VARIATIONAL QC WEIGHT ON PRESS. OBS BASED ON ANAL',\
'ROLF': 'AIRCRAFT ROLL ANGLE FLAG',\
'TQM': 'TEMPERATURE (QUALITY) MARKER',\
'AIRCFT': 'AIREP, PIREP, AMDAR, TAMDAR AIRCRAFT REPORTS',\
'HBOI': 'HEIGHT OF BASE OF ICING',\
'PRSLEVEL': 'PRESSURE LEVEL SEQUENCE (ALL TYPES EXCEPT GOESND)',\
'LATCORSQ': 'LATITUDE CORRECTION SEQUENCE',\
'HBOT': 'HEIGHT OF BASE OF TURBULENCE',\
'ZFC': 'FORECAST (BACKGROUND) HEIGHT VALUE',\
'QAN': 'ANALYZED SPECIFIC HUMIDITY VALUE',\
'Q___INFO': 'SPECIFIC HUMIDITY INFORMATION',\
'QIFY': 'PERCENT CONFIDENCE BASED ON EUMETSAT QUAL INDX W/ FCST',\
'P___INFO': 'PRESSURE INFORMATION',\
'SSTFC': 'FORECAST (BACKGROUND) SEA TEMPERATURE VALUE',\
'QIFN': 'PERCENT CONFIDENCE BASED ON EUMETSAT QUAL INDX W/O FCST',\
'TPRECSEQ': 'TOTAL PRECIPITATION SEQUENCE',\
'Z__POSTP': 'HEIGHT POSTPROCESSING SEQUENCE',\
'QRC': 'SPECIFIC HUMIDITY EVENT REASON CODE',\
'PTENDSEQ': 'PRESSURE TENDENCY SEQUENCE',\
'XWSPDSEQ': 'EXTRAPOLATED WIND SPEED SEQUENCE',\
'ZAN': 'ANALYZED HEIGHT VALUE',\
'RRTQM': 'RAINFALL (AVERAGE RATE) (QUALITY) MARKER',\
'PROFLR': 'WIND PROFILER REPORTS',\
'PWTPOSTP': 'TOTAL PRECIPITABLE WATER POSTPROCESSING SEQUENCE',\
'CHNM': 'CHANNEL NUMBER',\
'CTP_INFO': 'CLOUD TOP INFORMATION',\
'SSTAN': 'ANALYZED SEA TEMPERATURE VALUE',\
'PW3BACKG': '0.7 TO 0.3 SIGMA LAYER PRECIP WATER BACKGROUND SEQUENCE',\
'HOCT': 'HEIGHT OF TOP OF CLOUD',\
'SUNSHSEQ': 'TOTAL SUNSHINE SEQUENCE',\
'PRWE': 'PRESENT WEATHER',\
'XS10': '10 METER EXTRAPOLATED WIND SPEED',\
'NRLQMS': 'NRL AIRCRAFT QUALITY CNTRL MARK (ADDED BY PGM NRLACQC)',\
'PWF__MSQ': 'MODEL TOTAL PRECIPITABLE WATER FORECAST SEQUENCE',\
'Q__EVENT': 'SPECIFIC HUMIDITY EVENT SEQUENCE',\
'TCS': 'STANDARD DEVIATION OF CLIMATOLOGICAL TEMPERATURE VALUE',\
'TCL': 'CLIMATOLOGICAL TEMPERATURE VALUE',\
'W__BACKG': 'WIND BACKGROUND SEQUENCE',\
'XDR': 'PROFILE LEVEL LON (FOR RAOB/PIBAL BASED ON BALLOON DFT, DEG E)',\
'DOFS': 'DEPTH OF FRESH SNOW',\
'PFC__MSQ': 'MODEL PRESSURE FORECAST SEQUENCE',\
'SIRC': 'RAWINSONDE SOLAR & INFRARED RADIATION CORR. INDICATOR',\
'ZOB': 'HEIGHT OBSERVATION (M)',\
'ZOE': 'HEIGHT OBSERVATION ERROR (M)',\
'RSRD_SEQ': 'RESTRICTIONS ON REDISTRIBUTION SEQUENCE',\
'SATEMP': 'TOVS SATELLITE DATA (SOUNDINGS, RETRIEVALS, RADIANCES)',\
'SSTOE': 'SEA TEMPERATURE OBSERVATION ERROR',\
'DDO': 'WIND DIRECTION OBSERVATION (NOT ASSIMILATED)',\
'SSTPOSTP': 'SEA TEMPERATURE POSTPROCESSING SEQUENCE',\
'AFIC_SEQ': 'AIRCRAFT ICING SEQUENCE',\
'PCCF_SEQ': 'SATELLITE WIND PERCENT CONFIDENCE SEQUENCE',\
'CTPPOSTP': 'CLOUD TOP PRESSURE POSTPROCESSING SEQUENCE',\
'WSPD1': 'SURFACE WIND SPEED',\
'TRBX10': 'TURBULENCE INDEX FOR PERIOD (TOB-1 MIN) -> TOB',\
'SPRR': 'SEAWINDS PROBABILITY OF RAIN (QUIKSCAT REPORTS ONLY)',\
'LKCS': 'LIKELIHOOD COMPUTED FOR SOLUTION (ASCAT REPORTS ONLY)',\
'PRSLEVLG': 'GOESND PRESSURE LEVEL SEQUENCE',\
'OZON': 'OZONE',\
'CTPAN': 'ANALYZED CLOUD TOP PRESSURE VALUE',\
'R3DVAR': '3DVAR REGIONAL ANALYSIS STEP',\
'Z__EVENT': 'HEIGHT EVENT SEQUENCE',\
'PWFMOD': 'MODEL TOTAL PWATER FORECAST VALUE(GLOBAL MODEL SEE PWC)',\
'ASCATW': 'ASCAT SCATTEROMETER DATA (REPROCESSED)',\
'MRLWC': 'MWR LIQUID WATER CONTENT (TOTAL CLOUD LIQUID WATER)',\
'VISB1SEQ': 'VISIBILITY SEQUENCE # 1',\
'PW4_INFO': '0.3 TO 0.0 SIGMA LAYER PRECIPITABLE WATER INFORMATION',\
'TMBR': 'BRIGHTNESS TEMPERATURE (KELVIN)',\
'MXGD': 'MAXIMUM WIND GUST DIRECTION',\
'EEQF': 'PERCENT CONFIDENCE BASED ON NESDIS EXPECTED ERROR',\
'TVO': 'NON-Q. CONTROLLED VIRTUAL TEMP OBS (NOT ASSIMILATED)',\
'MXGS': 'MAXIMUM WIND SPEED (GUSTS, M/S)',\
'P__EVENT': 'PRESSURE EVENT SEQUENCE',\
'WDSATR': 'WINDSAT SCATTEROMETER DATA (REPROCESSED)',\
'REQV': 'RAINFALL (AVERAGE RATE) OBSERVATION',\
'QFCMOD': 'MODEL S. HUMIDITY FORECAST VALUE (GLOBAL MODEL SEE QFC)',\
'ATRN': 'ALONG TRACK ROW NUMBER (QUIKSCAT REPORTS ONLY)',\
'WDIR1': 'SURFACE WIND DIRECTION',\
'LONCORSQ': 'LONGITUDE CORRECTION SEQUENCE',\
'XORG': 'REPORTED (ORIGINAL) LONGITUDE',\
'RRTEVENT': 'RATE RATE EVENT SEQUENCE',\
'YORG': 'REPORTED (ORIGINAL) LATITUDE',\
'MWS10': 'MODEL WIND SPEED AT 10 M',\
'TDO': 'DEWPOINT TEMPERATURE OBSERVATION (NOT ASSIMILATED, DEGREES C)',\
'YDR': 'PROFILE LEVEL LAT (FOR RAOB/PIBAL BASED ON BALLOON DFT, DEG N)',\
'UFC': 'FORECAST (BACKGROUND) U-COMPONENT WIND VALUE',\
'W__POSTP': 'WIND POSTPROCESSING SEQUENCE',\
'SWINDSEQ': 'SURFACE WIND SEQUENCE',\
'PRSS': 'SURFACE PRESSURE OBSERVATION (PASCALS)',\
'SSTPC': 'SEA TEMPERATURE EVENT PROGRAM CODE',\
'WSPD_SEQ': 'WIND SPEED SEQUENCE',\
'VFCMOD': 'MODEL V-COMPONENT FORECAST VALUE (GLOBAL MODEL SEE VFC)',\
'AFIC': 'AIRFRAME ICING',\
'WSEQC1': 'WINDSAT EDR QC FLAG #1',\
'DOSW': 'DIRECTION OF SWELL WAVES',\
'PPC': 'PRESSURE EVENT PROGRAM CODE',\
'PWTBACKG': 'TOTAL PRECIPITABLE WATER BACKGROUND SEQUENCE',\
'VPRE': 'EST. ERROR COVARIANCE FOR TOTAL WATER VAPOR RETRIEVAL',\
'PWL_INFO': 'LAYER PRECIPITABLE WATER INFORMATION',\
'TVWTA': 'ANAL VARIATIONAL QC WEIGHT ON TEMP. OBS BASED ON ANAL',\
'PRSLEVLA': 'AIRCRAFT (AIRCFT/AIRCAR) PRESSURE LEVEL SEQUENCE',\
'HTOI': 'HEIGHT OF TOP OF ICING',\
'YOB': 'LATITUDE (DEG N)',\
'TVWTG': 'ANAL VARIATIONAL QC WEIGHT ON TEMP. OBS BASED ON GUESS',\
'HTOT': 'HEIGHT OF TOP OF TURBULENCE',\
'SSTBACKG': 'SEA TEMPERATURE BACKGROUND SEQUENCE',\
'UCS': 'STANDARD DEVIATION OF CLIMATOLOGICAL U-COMP WIND VALUE',\
'PWR': 'TOTAL PRECIPITABLE WATER EVENT REASON CODE',\
'PWP': 'TOTAL PRECIPITABLE WATER EVENT PROGRAM CODE',\
'PWQ': 'TOTAL PRECIPITABLE WATER (QUALITY) MARKER',\
'TP12': 'TOTAL PRECIPITATION PAST 12 HOURS',\
'3HPC': '3 HOUR PRESSURE CHANGE',\
'PWF': 'FORECAST (BACKGROUND) TOTAL PRECIPITABLE WATER VALUE',\
'PWE': 'TOTAL PRECIPITABLE WATER OBSERVATION ERROR (MM)',\
'QKSWND': 'QUIKSCAT SCATTEROMETER DATA (REPROCESSED)',\
'TRBX43': 'TURBULENCE INDEX FOR PERIOD (TOB-4 MIN) -> (TOB-3 MIN)',\
'PWO': 'TOTAL PRECIPITABLE WATER OBSERVATION (MM)',\
'TRBX': 'TURBULENCE INDEX',\
'PW3FMOD': 'MODEL .7-.3 SIG. LYR PWATER FCST(GLOBAL MODEL SEE PW3F)',\
'GSI': 'GSI ANALYSIS STEP',\
'A1': 'ERS INCIDENT ANGLE NUMBER 1',\
'RRTRC': 'RAINFALL (AVERAGE RATE) EVENT REASON CODE',\
'QVWTA': 'ANAL VARIATIONAL QC WEIGHT ON MOIST. OBS BASED ON ANAL',\
'TFCMOD': 'MODEL TEMPERATURE FORECAST VALUE (GLOBAL MODEL SEE TFC)',\
'QVWTG': 'ANAL VARIATIONAL QC WEIGHT ON MOIST. OBS BASED ON GUESS',\
'SPDE': 'EST. ERROR COVARIANCE FOR WIND SPEED RETRIEVAL',\
'CTPBACKG': 'CLOUD TOP PRESSURE BACKGROUND SEQUENCE',\
'GCDTT': 'GOES CLOUD TOP TEMPERATURE OBSERVATION',\
'PW3R': '0.7 TO 0.3 SIGMA LAYER PRECIP. WATER EVENT REASON CODE',\
'PW3P': '0.7 TO 0.3 SIGMA LAYER PRECIP. WATER EVENT PROGRAM CODE',\
'PW3Q': '0.7 TO 0.3 SIGMA LAYER PRECIP. WATER (QUALITY) MARKER',\
'PW3F': 'FCST(BACKGRND) 0.7 TO 0.3 SIGMA LYR PRECIP. WATER VALUE',\
'PW3E': '0.7 TO 0.3 SIGMA LAYER PRECIP. WATER OBSERVATION ERROR',\
'PW3A': 'ANALYZED 0.7 TO 0.3 SIGMA LAYER PRECIP. WATER VALUE',\
'PW3O': '0.7 TO 0.3 SIGMA LAYER PRECIPITABLE WATER OBSERVATION',\
'ZPC': 'HEIGHT EVENT PROGRAM CODE',\
'UCL': 'CLIMATOLOGICAL U-COMPONENT WIND VALUE',\
'PW1BACKG': '1.0 TO 0.9 SIGMA LAYER PRECIP WATER BACKGROUND SEQUENCE',\
'SQN': 'REPORT SEQUENCE NUMBER',\
'B2': 'ERS AZIMUTH  ANGLE NUMBER 2',\
'B3': 'ERS AZIMUTH  ANGLE NUMBER 3',\
'PWT_INFO': 'TOTAL PRECIPITABLE WATER INFORMATION',\
'PW4BACKG': '0.3 TO 0.0 SIGMA LAYER PRECIP WATER BACKGROUND SEQUENCE',\
'SWELLSEQ': 'SWELL WAVE SEQUENCE',\
'CLTP': 'CLOUD TYPE',\
'GOESND': 'GOES SATELLITE DATA (SOUNDINGS, RETRIEVALS, RADIANCES)',\
'WAVE_SEQ': 'WAVE SEQUENCE',\
'PW1_INFO': '1.0 TO 0.9 SIGMA LAYER PRECIPITABLE WATER INFORMATION',\
'PW3_INFO': '0.7 TO 0.3 SIGMA LAYER PRECIPITABLE WATER INFORMATION',\
'WSST': 'WINDSAT SURFACE TYPE',\
'CQCPROF': 'WIND PROFILER QUALITY CONTROL STEP',\
'BTMPLEVL': 'BRIGHTNESS TEMPERATURE "LEVEL" SEQUENCE',\
'W___INFO': 'WIND INFORMATION',\
'VTVI': 'VERTICAL VISIBILITY',\
'MXTM': 'MAXIMUM TEMPERATURE',\
'SPRVSTG': 'MESONET SUBPROVIDER ID STRING',\
'B1': 'ERS AZIMUTH  ANGLE NUMBER 1',\
'TCOR': 'INDICATOR WHETHER OBS. TIME IN "DHR" WAS CORRECTED',\
'PSTWXSEQ': 'PAST WEATHER SEQUENCE',\
'AIRCAR': 'MDCRS ACARS AIRCRAFT REPORTS',\
'TRC': 'TEMPERATURE EVENT REASON CODE',\
'TOPC_SEQ': 'TOTAL PRECIPITATION/TOTAL WATER EQUIVALENT SEQUENCE',\
'T__BACKG': 'TEMPERATURE BACKGROUND SEQUENCE',\
'T29': 'DATA DUMP REPORT TYPE',\
'T___INFO': 'TEMPERATURE INFORMATION',\
'PW3F_MSQ': 'MODEL 0.7 TO 0.3 SIGMA LAYER PRECIP WATER FORECAST SEQ.',\
'VOB': 'V-COMPONENT WIND OBSERVATION (M/S)',\
'QCLIMATO': 'SPECIFIC HUMIDITY CLIMATOLOGY SEQUENCE',\
'OIQC': 'OI-QUALITY MULTI-PLATFROM CONTROL STEP',\
'PMSL_SEQ': 'MEAN SEA LEVEL PRESSURE SEQUENCE',\
'WVCQ': 'WIND VECTOR CELL QUALITY (ASCAT REPORTS ONLY)',\
'DEFAULT': 'NON-DEFINED STEP (DEFAULT)',\
'TOCC': 'CLOUD COVER (TOTAL)',\
'SST1': 'SEA TEMPERATURE',\
'ACAV': 'TOTAL NUMBER WITH RESPECT TO ACCUMULATION OR AVERAGE',\
'CTPRC': 'CLOUD TOP PRESSURE EVENT REASON CODE',\
'PRVSTG': 'MESONET PROVIDER ID STRING',\
'TRBX21': 'TURBULENCE INDEX FOR PERIOD (TOB-2 MIN) -> (TOB-1 MIN)',\
'PMQ': 'MEAN SEA-LVL PRESSURE (QUALITY) MARKER',\
'DBSS_SEQ': 'DEPTH BELOW SEA SURFACE SEQUENCE',\
'MSONET': 'MESONET SURFACE REPORTS (COOPERATIVE NETWORKS)',\
'PMO': 'MEAN SEA-LEVEL PRESSURE OBSERVATION (MB)',\
'PWTEVENT': 'TOTAL PRECIPITABLE WATER EVENT SEQUENCE',\
'PW4POSTP': '0.3 TO 0.0 SIGMA LAYER PRECIP WATER POSTPROCESSING SEQ.',\
'TMSK': 'SKIN TEMPERATURE',\
'CLOU2SEQ': 'OBSERVED CLOUD SEQUENCE # 2',\
'PW2F_MSQ': 'MODEL 0.9 TO 0.7 SIGMA LAYER PRECIP WATER FORECAST SEQ.',\
'WVWTG': 'ANAL VARIATIONAL QC WEIGHT ON WIND OBS BASED ON GUESS',\
'ELV': 'STATION ELEVATION (M)',\
'WVWTA': 'ANAL VARIATIONAL QC WEIGHT ON WIND OBS BASED ON ANAL',\
'ZFCMOD': 'MODEL HEIGHT FORECAST VALUE (GLOBAL MODEL SEE ZFC)',\
'RSRD': 'RESTRICTIONS ON REDISTRIBUTION',\
'PREPACQC': 'AIRCRAFT QUALITY CONTROL STEP (NOT INCL. MDCRS ACARS)',\
'SSTE': 'EST. ERROR COVARIANCE FOR SEA SURFACE TEMP RETRIEVAL',\
'QCS': 'STANDARD DEV OF CLIMATOLOGICAL SPECIFIC HUMIDITY VALUE',\
'ZCLIMATO': 'HEIGHT CLIMATOLOGY SEQUENCE',\
'PCAT': 'PRECISION OF TEMPERATURE OBSERVATION',\
'QCL': 'CLIMATOLOGICAL SPECIFIC HUMIDITY VALUE',\
'PW4EVENT': '0.3 TO 0.0 PRECIPITABLE WATER EVENT SEQUENCE',\
'HOWV': 'HEIGHT OF WAVES',\
'HOWW': 'HEIGHT OF WIND WAVES',\
'CQCHT': 'RAWINSONDE HEIGHT/TEMP COMPLEX QUALITY CONTROL STEP',\
'RRTAN': 'ANALYZED RAINFALL (AVERAGE RATE) VALUE',\
'A3': 'ERS INCIDENT ANGLE NUMBER 3',\
'A2': 'ERS INCIDENT ANGLE NUMBER 2',\
'ALSE': 'ALTIMETER SETTING OBSERVATION',\
'HOCB': 'HEIGHT OF BASE OF CLOUD',\
'SSTEVENT': 'SEA TEMPERATURE EVENT SEQUENCE',\
'SQM': 'WIND SPEED (SOB) (QUALITY) MARKER',\
'Q__BACKG': 'SPECIFIC HUMIDITY BACKGROUND SEQUENCE',\
'PROCN': 'PROCESS NUMBER FOR THIS MPI RUN (OBTAINED FROM SCRIPT)',\
'HBLCS': 'HEIGHT ABOVE SURFACE OF BASE OF LOWEST CLOUD SEEN',\
'RRT_INFO': 'RAIN RATE INFORMATION',\
'PW2EVENT': '0.9 TO 0.7 PRECIPITABLE WATER EVENT SEQUENCE',\
'Z__BACKG': 'HEIGHT BACKGROUND SEQUENCE',\
'PFC': 'FORECAST (BACKGROUND) PRESSURE VALUE',\
'ZCL': 'CLIMATOLOGICAL HEIGHT VALUE',\
'SHIP_SEQ': 'SHIP DIRECTION/SPEED SEQUENCE',\
'VSSO': 'VERT. SIGNIFICANCE (SFC OBSERVATION)',\
'DRFTINFO': 'PROFILE LEVEL TIME/LOCATION INFORMATION',\
'ZCS': 'STANDARD DEVIATION OF CLIMATOLOGICAL HEIGHT VALUE',\
'DBSS': 'DEPTH BELOW SEA SURFACE'
}
'''dictionary mapping prepbufr mnemonics to human readable descriptions'''
