#!/usr/bin/env python
from __future__ import print_function
import ncepbufr
import numpy as np
from netCDF4 import Dataset
from ncepbufr import prepbufr_mnemonics_dict as mnemonics_dict
import sys

if len(sys.argv) < 3:
    raise SystemExit('prepbufr2nc <input prepbufr> <output netcdf>')
# input and output file names from command line args.
prepbufr_filename = sys.argv[1]
netcdf_filename = sys.argv[2]
if prepbufr_filename == netcdf_filename:
    raise IOError('cannot overwrite input prepbufr file')

# chunksize along leftmost dimension for netcdf
nobschunk = 100

# mnemonics to extract data from prepbufr file.
hdstr='SID XOB YOB DHR TYP ELV SAID T29'
obstr='POB QOB TOB ZOB UOB VOB PWO MXGS HOVI CAT PRSS TDO PMO XDR YDR HRDR'
qcstr='PQM QQM TQM ZQM WQM PWQ PMQ'
oestr='POE QOE TOE ZOE WOE PWE'

# skip these report types
skiptypes = []
#skiptypes = ['SATWND']

# open netcdf file
nc = Dataset(netcdf_filename,'w',format='NETCDF4')
hd = nc.createDimension('hdrinfo',len(hdstr.split())-1)
nhdd = len(hd)
ob = nc.createDimension('obinfo',len(obstr.split()))
nobd = len(ob)
oe = nc.createDimension('oeinfo',len(oestr.split()))
noed = len(oe)
qc = nc.createDimension('qcinfo',len(qcstr.split()))
nqcd = len(qc)
levs = nc.createDimension('datalevs',255)
nlevs = len(levs)

# open prepbufr file.
bufr = ncepbufr.open(prepbufr_filename)

# find number of messages, obs for each message type in bufr file.
typedict = {}
while bufr.advance() == 0: # loop over messages.
    if bufr.msg_type in skiptypes: continue
    if bufr.msg_type not in typedict.keys():
        typedict[bufr.msg_type] = 0
    while bufr.load_subset() == 0: # loop over subsets in message.
        typedict[bufr.msg_type] += 1
nmessages = bufr.msg_counter
bufr.rewind()

# create some more variables in the netcdf file (that pertain to messages).
nm = nc.createDimension('msg',nmessages)
msg_date =\
nc.createVariable('msg_date',np.int32,('msg',),fill_value=-1,zlib=True)
msg_date.desc = 'BUFR MESSAGE DATE'

# read prepbufr data, write to netcdf.
nobsdict = {}
obs2 = bufr.missing_value*np.ones((nobd,nlevs),np.float)
err2 = bufr.missing_value*np.ones((noed,nlevs),np.float)
qc2 = bufr.missing_value*np.ones((nqcd,nlevs),np.float)
while bufr.advance() == 0: # loop over messages.
    if bufr.msg_type in skiptypes: continue
    # nobsdict used to keep track of number of obs written
    # for each message type.
    if bufr.msg_type not in nobsdict.keys():
        nobsdict[bufr.msg_type] = -1
    nmsg = bufr.msg_counter
    msg_date[nmsg-1] = bufr.msg_date
    # each message type in a separate group.
    if bufr.msg_type not in nc.groups:
        g = nc.createGroup(bufr.msg_type)
        g.setncattr('desc',mnemonics_dict[bufr.msg_type].rstrip())
        # number of obs is the unlimited dimension.
        nobsd = g.createDimension('nobs',typedict[bufr.msg_type])
        # chunksize should not be greater than the number of obs.
        nobs_chunk = min(len(nobsd),nobschunk)
        hdrdata =\
        g.createVariable('header',np.float32,('nobs','hdrinfo'),\
	fill_value=bufr.missing_value,zlib=True,chunksizes=(nobs_chunk,nhdd))
        stnid = g.createVariable('stationid',str,('nobs',))
        stnid.desc = 'STATION IDENTIFICATION'
        # retain association of ob data with bufr message number.
        msgnum = g.createVariable('msgnum',np.int32,('nobs',))
        msgnum.desc = 'BUFR MESSAGE NUMBER'
        for key in hdstr.split()[1:]:
            hdrdata.setncattr(key,mnemonics_dict[key])
        hdrdata.hdrinfo = hdstr[4:]
        if bufr.msg_type in ['RASSDA','VADWND','PROFLR','ADPUPA']:
            # these message types are multi-level
            obdata =\
            g.createVariable('obdata',np.float32,('nobs','obinfo','datalevs'),\
            fill_value=bufr.missing_value,zlib=True,chunksizes=(nobs_chunk,nobd,nlevs))
            oedata =\
            g.createVariable('oberr',np.float32,('nobs','oeinfo','datalevs'),\
            fill_value=bufr.missing_value,zlib=True,chunksizes=(nobs_chunk,noed,nlevs))
            qcdata =\
            g.createVariable('qcdata',np.float32,('nobs','qcinfo','datalevs'),\
            fill_value=bufr.missing_value,zlib=True,chunksizes=(nobs_chunk,nqcd,nlevs))
        else:
            # single level message types.
            obdata =\
            g.createVariable('obdata',np.float32,('nobs','obinfo'),\
            fill_value=bufr.missing_value,zlib=True,chunksizes=(nobs_chunk,nobd))
            oedata =\
            g.createVariable('oberr',np.float32,('nobs','oeinfo'),\
            fill_value=bufr.missing_value,zlib=True,chunksizes=(nobs_chunk,noed))
            qcdata =\
            g.createVariable('qcdata',np.float32,('nobs','qcinfo'),\
            fill_value=bufr.missing_value,zlib=True,chunksizes=(nobs_chunk,nqcd))
        # mnemonic descriptions as variable attributes.
        for key in obstr.split():
            obdata.setncattr(key,mnemonics_dict[key])
        obdata.obinfo = obstr
        for key in oestr.split():
            oedata.setncattr(key,mnemonics_dict[key])
        oedata.oeinfo = oestr
        for key in qcstr.split():
            qcdata.setncattr(key,mnemonics_dict[key])
        qcdata.qcinfo = qcstr
    # lists to hold data from each subset
    hdrarr = []; obsarr = []; qcarr = []; errarr = []; stnidarr = []
    while bufr.load_subset() == 0: # loop over subsets in message.
        hdr = bufr.read_subset(hdstr).squeeze()
        obs = bufr.read_subset(obstr)
        qc  = bufr.read_subset(qcstr)
        err = bufr.read_subset(oestr)
        nl = obs.shape[-1] # number of levels in data.
        nobsdict[bufr.msg_type] += 1 # ob number for this message type.
        # station id in a separate variables.
        hdrarr.append(hdr.squeeze()[1:])
        stnidarr.append(hdr[0].tostring())
        if bufr.msg_type in ['RASSDA','VADWND','PROFLR','ADPUPA']:
            # multi-level data.
            obs2[:] = bufr.missing_value; obs2[:,:nl] = obs
            obsarr.append(obs2)
            err2[:] = bufr.missing_value; err2[:,:nl] = err
            errarr.append(err2)
            qc2[:] = bufr.missing_value; qc2[:,:nl] = qc
            qcarr.append(qc2)
        else:
            # single level data.
            obsarr.append(obs.squeeze())
            errarr.append(err.squeeze())
            qcarr.append(qc.squeeze())
    # make lists into arrays.
    nob = nobsdict[bufr.msg_type]
    nob1 = nob-bufr.subsets+1
    print('writing message %s out of %s, type %s with %s obs' %\
    (bufr.msg_counter,nmessages,bufr.msg_type,bufr.subsets))
    # write all the data from subset.
    g['header'][nob1:nob+1] = np.array(hdrarr)
    g['obdata'][nob1:nob+1] = np.array(obsarr)
    g['oberr'][nob1:nob+1]  = np.array(errarr)
    g['qcdata'][nob1:nob+1] = np.array(qcarr)
    g['stationid'][nob1:nob+1] = np.array(stnidarr)
    # keep track of message number
    g['msgnum'][nob1:nob+1] = bufr.msg_counter
    nc.sync() # dump data to disk.

# close files.
bufr.close(); nc.close()
